### ISSUE TITLE
some UI bugs

### ISSUE THREAD

**Issue by 3m4r5** [DannyMoerkerke/whatpwacando.today#20] opened 2022-05-01 06:35 UTC
~~1- in Speech recognition, the page is Swipeable horizontally because the result text box is wider than the screen (tested on iPhone 8 Plus).~~ fixed

~~2- in Speech recognition, the result text box is fillable by the user but shouldn't.~~ fixed

~~3- in dark mode, the color of the bottom bar icons and text is white, which is inconsistent with the rest of the ui elements.~~ (minor)

4- the top ~~and bottom~~ bar~~s~~ is swipeable which creates [annoying behavior](https://user-images.githubusercontent.com/63432932/172892075-d645ec2a-23d2-4b37-9408-acc92a0ff09f.MOV) when trying to swipe.

~~5- when I reload, the "Your device is currently offline." message disappears.~~ fixed

~~6- when I get "Geolocation error", the background is still swipeable.~~ fixed

~~7- in the Info section, the form in the bottom is wider than the screen.~~ fixed

~~8- in Audio recording, the volume slider isn't swipeable.~~

~~9- [this](https://user-images.githubusercontent.com/63432932/166135339-2245a36c-e34b-426a-8f53-27810f8ea4cc.MOV).~~ fixed

~~10- when I reload while offline usually I get [this](https://user-images.githubusercontent.com/63432932/167927994-882a3c36-2c4f-47bf-bd5e-c74747de6ac6.png), but I couldn't reproduce this behavior while recording the screen.~~

~~11- sometimes I get [this](https://user-images.githubusercontent.com/63432932/167932012-53fdf951-c997-49a6-bad0-54541f05b597.MOV) while offline.~~ (can't reproduce)

~~12- [screen recording](https://user-images.githubusercontent.com/63432932/172891265-3e0a7d7a-78ac-46ce-9417-ce34d75e9e63.MOV)~~ fixed

~~13- is [this](https://user-images.githubusercontent.com/63432932/172891454-ea910027-a455-4d69-954f-ed3a7c33061a.MOV) supposed to happen this quickly?~~ can't reproduce

**Comment by DannyMoerkerke** [comment] 2022-05-10 14:04
Thanks for reporting!

I fixed all bugs except:

3) what should the correct colors be according to you?
8) I can adjust the volume on my iPhone 13, I'll see if I can check on iPhone 8. What do you mean with recording slider? If you mean the vertical bar in the waveform view, this is not supposed to be swipeable.
9) I cannot reproduce this. Is the audio not loading in the Audio demo?

**Comment by 3m4r5** [comment] 2022-05-11 19:33
> 3) what should the correct colors be according to you?

idk maybe #EAEAEA like the rest of the icons, but you may want to leave it as it is to make it pop more than the other buttons, either way it's not significant.

> 8) I can adjust the volume on my iPhone 13, I'll see if I can check on iPhone 8.

turns out the audio slider is functional and swipeable but it's small and slightly hard to grip therefore I thought it's a bug.

> What do you mean with recording slider? If you mean the vertical bar in the waveform view, this is not supposed to be swipeable.

I thought it was supposed to be swipeable.

> 9) I cannot reproduce this. Is the audio not loading in the Audio demo?

not sure which issue are you talking about if it's about #9 it's a ui bug, all I have to do to reproduce it is to go into any section and then tap on reload and then tap on the left-pointing arrow at the top.

the audio demo is loading fine (while online)

and the audio playback in the recording demo seems to be fixed.

**Comment by DannyMoerkerke** [comment] 2022-05-25 07:22
Just pushed the fixes, all should now be fixed.

**Comment by 3m4r5** [comment] 2022-06-09 15:59
@DannyMoerkerke I still can reproduce number 9

**Comment by DannyMoerkerke** [comment] 2022-06-24 07:15
@3m4r5 I fixed #9.

12 should now also be fixed but what iOS version are you on?

13 what exactly are you doing here? The video is very short and I can't see what's in the top of the screen.

**Comment by 3m4r5** [comment] 2022-06-24 10:18
@DannyMoerkerke in #13 I just disabled wifi and then tapped on reload, I can't reproduce it anymore.

**Comment by 3m4r5** [comment] 2022-06-24 10:32
I'm on iOS 14.7.1

**Comment by DannyMoerkerke** [comment] 2022-06-24 13:52
Then all issues should be fixed now. If you spot any issues again please let me know.

Thanks so much for reporting!

**Closed as completed by DannyMoerkerke** 2022-06-24 13:52 UTC
