### ISSUE TITLE
The bottom nav bar gets cut off sometimes

### ISSUE THREAD

**Issue by jeffslofish** [DannyMoerkerke/whatpwacando.today#3] opened 2020-03-16 04:49 UTC
I noticed that after trying "Media capture" or "AR/VR", the bottom nav bar would start moving with the page as I scroll it up and down and remains stuck halfway past the bottom of the screen until the app is killed and restarted.  This is on an iOS device.

![IMG_2573E3D4B7FF-1](https://user-images.githubusercontent.com/1240484/76724004-9c6bda00-6706-11ea-8358-bd2378e18ba8.jpeg)

**Comment by DannyMoerkerke** [comment] 2020-03-16 17:48
I’m not able to reproduce this. Could you please provide some more context? Thanks for reporting!

**Comment by jeffslofish** [comment] 2020-03-16 21:23
Here are my steps to reproduce:

1. Launch app
2. Click "Media capture" button
3. Click video icon in lower left area of white box
4. Click cancel

After clicking cancel, the screen immediately goes to what is displayed above. Interestingly, it only has this behavior in portrait mode, not landscape.

This testing was done on an iPhone 8 plus.

**Comment by DannyMoerkerke** [comment] 2020-03-17 21:52
I managed to reproduce this on an iPhone 6 and iPhone 8. 
It seems to be a layout bug that happens only in standalone mode (when installed to the home screen) and not in the browser.

Somehow, the height of the status bar is added to the total height and the footer is pushed below the fold. It is possible to drag it back up, pushing the header partially under the status bar.
I'm investigating further.

**Comment by DannyMoerkerke** [comment] 2020-03-17 23:31
This had now been fixed in the latest release.
I managed to fix it by removing `viewport-fit=cover` from the `content` meta tag and only adding this for iPhone X and higher.
It does involve some user agent sniffing I'm not particularly happy with but for now it fixes the issue and I will look for a better solution.

**Closed as completed by DannyMoerkerke** 2020-03-17 23:31 UTC
Labels: bug, help wanted
