### ISSUE TITLE
doesnt work when phone is not connected to interner

### ISSUE THREAD

**Issue by chrisjameslennon** [DannyMoerkerke/whatpwacando.today#5] opened 2020-04-29 09:46 UTC
When I am in flight mode and open the app I get a "cannot connect to site" error message and the app doesnt open.

To support offline mode

I am using samsung S8

**Comment by DannyMoerkerke** [comment] 2020-04-29 09:58
Hi Chris, thanks for reporting. 
Did you already open the app at least once before trying to open in offline?

**Comment by Gareth10jones** [comment] 2020-04-29 13:44
I see the same issue, even after having opened the app, closing, disabling data then reopening.  Error displayed is:

_"FetchEvent.respondWith received an error: TypeError: The internet connection appears to be offline"._

Great idea by the way and very useful!

**Comment by DannyMoerkerke** [comment] 2020-04-29 16:11
I’m not able to reproduce this so far. Even with a fresh install and only opening the home screen, then going offline, all pages load. 
Can you still reproduce or share the steps how to reproduce it?

**Comment by Gareth10jones** [comment] 2020-04-29 17:03
Does this help... https://we.tl/t-ucXMTBckU3

**Comment by DannyMoerkerke** [comment] 2020-04-29 18:23
Interesting... I am able to reproduce it now on iOS13.
This was working before so I'll check and get back to you.

**Comment by Gareth10jones** [comment] 2020-04-29 22:09
Ok great.  Glad I can help and no pressure from my side, was just confirming what @cjlennon was reporting.

**Comment by DannyMoerkerke** [comment] 2020-04-30 20:54
Fixed and now released!

**Closed as completed by DannyMoerkerke** 2020-04-30 20:54 UTC

**Comment by chrisjameslennon** [comment] 2020-05-01 00:20
yup working now nice one!

**Comment by Gareth10jones** [comment] 2020-05-01 07:50
working for me too! Cheers!
